Error: failed external call: CWE191_Integer_Underflow__int_fscanf_sub_53b_goodG2BSink
Stack: 
	#000000645 in goodG2B()
	#100000634 in CWE191_Integer_Underflow__int_fscanf_sub_53_good()
	#200000668 in __user_main()
	#300000441 in __uClibc_main(136244134170624, 1, 136259401437184, 0, 0, 0, 0) at libc/misc/internals/__uClibc_main.c:401
	#400000613 in main(1, 136259401437184)
